# Generated by Django 3.1.1 on 2020-09-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='c_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
