# Generated by Django 3.1.1 on 2020-11-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200921_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_details',
        ),
    ]
