# Generated by Django 3.1.1 on 2020-09-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subcategory'),
        ),
    ]
