# Generated by Django 3.1.1 on 2020-10-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201007_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='division',
            new_name='city',
        ),
    ]
