# Generated by Django 3.1.1 on 2020-10-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201007_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
    ]
