# Generated by Django 3.1.1 on 2020-10-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201007_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.area'),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.district'),
        ),
    ]
