# Generated by Django 3.1.1 on 2020-11-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201007_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=20)),
                ('instagram', models.CharField(max_length=20)),
                ('youtube', models.CharField(max_length=20)),
            ],
        ),
    ]
