# Generated by Django 3.1.1 on 2020-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(default=None, upload_to='main/sites'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
