# Generated by Django 3.1.1 on 2020-11-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201112_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='tagline',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
