# Generated by Django 3.1.1 on 2020-11-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_siteinfo_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('used', 'Used'), ('new', 'New')], default='used', max_length=10),
            preserve_default=False,
        ),
    ]
