# Generated by Django 3.1.1 on 2020-11-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200930_1641'),
        ('main', '0013_auto_20201117_0317'),
    ]

    operations = [
    ]
